// Venue rosters for the two hackathon slots (see SCHEDULE in curiosity-reveal.tsx: slot 1 runs
// Sep 3-6, slot 2 runs Sep 11-13). Images live under /public/venues/slot-{1,2}, webp at a 900px
// long edge - the reveal draws them as ~68px tiles, so anything bigger is bytes nobody sees.
export const VENUES = [
  { name: "MITS", slot: 1, image: "/venues/slot-1/mits.webp" },
  { name: "CE Vadakara", slot: 1, image: "/venues/slot-1/ce-vadakara.webp" },
  { name: "Devagiri", slot: 1, image: "/venues/slot-1/devagiri.webp" },
  { name: "FISAT", slot: 1, image: "/venues/slot-1/fisat.webp" },
  { name: "Jain", slot: 1, image: "/venues/slot-1/jain.webp" },
  { name: "Kalloopara", slot: 1, image: "/venues/slot-1/kalloopara.webp" },
  { name: "LBS Poojapura", slot: 1, image: "/venues/slot-1/lbs-poojapura.webp" },
  { name: "MEC Thrikkakara", slot: 1, image: "/venues/slot-1/mec-thrikkakara.jpeg" },
  { name: "Sahrdaya", slot: 1, image: "/venues/slot-1/sahrdaya.webp" },
  { name: "Saintgits", slot: 1, image: "/venues/slot-1/saintgits.webp" },
  { name: "SCMS", slot: 1, image: "/venues/slot-1/scms.webp" },
  { name: "Sree Buddha Pattoor", slot: 1, image: "/venues/slot-1/sree-buddha-pattoor.webp" },
  { name: "Tinkerspace", slot: 1, image: "/venues/slot-1/tinkerspace.webp" },
  { name: "Viswajyothi", slot: 1, image: "/venues/slot-1/viswajyothi.webp" },
  { name: "ACE", slot: 2, image: "/venues/slot-2/ace.webp" },
  { name: "Adi Shankara", slot: 2, image: "/venues/slot-2/adi-shankara.webp" },
  { name: "Adoor", slot: 2, image: "/venues/slot-2/adoor.webp" },
  { name: "Ahalia", slot: 2, image: "/venues/slot-2/ahalia.webp" },
  { name: "AISAT", slot: 2, image: "/venues/slot-2/aisat.webp" },
  { name: "Al Azhar", slot: 2, image: "/venues/slot-2/al-azhar.webp" },
  { name: "Ansar", slot: 2, image: "/venues/slot-2/ansar.webp" },
  { name: "Attingal", slot: 2, image: "/venues/slot-2/attingal.webp" },
  { name: "Baselious Marthoma", slot: 2, image: "/venues/slot-2/baselious-marthoma.webp" },
  { name: "Carmel", slot: 2, image: "/venues/slot-2/carmel.webp" },
  { name: "CET", slot: 2, image: "/venues/slot-2/cet.webp" },
  { name: "Chengannur", slot: 2, image: "/venues/slot-2/chengannur.webp" },
  { name: "Christ", slot: 2, image: "/venues/slot-2/christ.webp" },
  { name: "Cochin Kuttanad", slot: 2, image: "/venues/slot-2/cochin-kuttanad.webp" },
  { name: "Duxford", slot: 2, image: "/venues/slot-2/duxford.webp" },
  { name: "EMEA", slot: 2, image: "/venues/slot-2/emea.webp" },
  { name: "Farook", slot: 2, image: "/venues/slot-2/farook.webp" },
  { name: "FISAT", slot: 2, image: "/venues/slot-2/fisat.webp" },
  { name: "GEC Thrissur", slot: 2, image: "/venues/slot-2/gec-thrissur.webp" },
  { name: "Gurukulam", slot: 2, image: "/venues/slot-2/gurukulam.webp" },
  { name: "ICCS", slot: 2, image: "/venues/slot-2/iccs.webp" },
  { name: "Ilahia", slot: 2, image: "/venues/slot-2/ilahia.webp" },
  { name: "Jawharlal", slot: 2, image: "/venues/slot-2/jawharlal.webp" },
  { name: "Jyothi", slot: 2, image: "/venues/slot-2/jyothi.webp" },
  { name: "KAHM", slot: 2, image: "/venues/slot-2/kahm.webp" },
  { name: "Karunagapally", slot: 2, image: "/venues/slot-2/karunagapally.webp" },
  { name: "KMEA", slot: 2, image: "/venues/slot-2/kmea.webp" },
  { name: "LBS Povval", slot: 2, image: "/venues/slot-2/lbs-povval.webp" },
  { name: "Lourde", slot: 2, image: "/venues/slot-2/lourde.webp" },
  { name: "Majlis", slot: 2, image: "/venues/slot-2/majlis.webp" },
  { name: "MAMOC", slot: 2, image: "/venues/slot-2/mamoc.webp" },
  { name: "Mar Athanasius", slot: 2, image: "/venues/slot-2/mar-athanasius.webp" },
  { name: "MBCCET", slot: 2, image: "/venues/slot-2/mbccet.webp" },
  { name: "MES Kunnukara", slot: 2, image: "/venues/slot-2/mes-kunnukara.webp" },
  { name: "Munnar", slot: 2, image: "/venues/slot-2/munnar.webp" },
  { name: "NSS Akathethara", slot: 2, image: "/venues/slot-2/nss-akathethara.webp" },
  { name: "Perumon", slot: 2, image: "/venues/slot-2/perumon.webp" },
  { name: "Poonjar", slot: 2, image: "/venues/slot-2/poonjar.webp" },
  { name: "Providence Chengannur", slot: 2, image: "/venues/slot-2/providence-chengannur.webp" },
  { name: "Punnapra", slot: 2, image: "/venues/slot-2/punnapra.webp" },
  { name: "RIT", slot: 2, image: "/venues/slot-2/rit.webp" },
  { name: "Sahrdaya", slot: 2, image: "/venues/slot-2/sahrdaya.webp" },
  { name: "Saintgits Engineering", slot: 2, image: "/venues/slot-2/saintgits-engg.webp" },
  { name: "SJCET", slot: 2, image: "/venues/slot-2/sjcet.webp" },
  { name: "SNM", slot: 2, image: "/venues/slot-2/snm.webp" },
  { name: "SOE CUSAT", slot: 2, image: "/venues/slot-2/soe-cusat.webp" },
  { name: "Sree Chithra", slot: 2, image: "/venues/slot-2/sree-chithra.webp" },
  { name: "Sree Narayana Guru Chalakode", slot: 2, image: "/venues/slot-2/sree-narayana-guru-chalakode.webp" },
  { name: "St Thomas Ranni", slot: 2, image: "/venues/slot-2/st-thomas-ranni.webp" },
  { name: "Thejus", slot: 2, image: "/venues/slot-2/thejus.webp" },
  { name: "Thenhipalam", slot: 2, image: "/venues/slot-2/thenhipalam.webp" },
  { name: "TKM", slot: 2, image: "/venues/slot-2/tkm.webp" },
  { name: "TOC H", slot: 2, image: "/venues/slot-2/toc-h.webp" },
  { name: "Trikaripur", slot: 2, image: "/venues/slot-2/trikaripur.webp" },
  { name: "TS Calicut", slot: 2, image: "/venues/slot-2/ts-calicut.webp" },
  { name: "Vidya Academy", slot: 2, image: "/venues/slot-2/vidya-academy.webp" },
  { name: "Vimal Jyothi", slot: 2, image: "/venues/slot-2/vimal-jyothi.webp" },
  { name: "West Hill", slot: 2, image: "/venues/slot-2/west-hill.webp" },
] as const;
